Practica2/Blog/urls.py
from django.urls import path

from . import views

app_name = 'Blog'

urlpatterns =[
    path('', views.index, name='index'),
    path('categoria/<int:categoria_id>', views.cat_post, name='cat_post')
]

Practica2/Practica2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Blog/', include('Blog.urls'))
]

Practica2/Blog/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    def __str__(self):
        return self.nombre

class Post(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

Practica2/Blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
# Create your views here.
def index(request):
    categories_list = Categoria.objects.all()
    post_list = Post.objects.all()
    context = {'catgories_list': categories_list,
               'post_list':post_list}
    return render(request, 'index.html',context)

def cat_post(request, categoria_id):
    categories_list = Categoria.objects.all()
    category = get_object_or_404(Categoria, pk=categoria_id)
    return render(request, 'index.html',{'catgories_list':categories_list,'categoria':category})

Practica2/Blog/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Nested row for non-featured blog posts-->
                    <div class="row">
                            <!-- Blog post-->

                        {% if categoria %}
                            {%for post in categoria.post_set.all%}
                            <div class="card mb-4">
                                <div class="card-body">
                                    <h2 class="card-title h4">{{post.titulo}}</h2>
                                    <p class="card-text">{{post.descripcion}}</p>
                                </div>
                            </div>
                        {% endfor %}
                        {% else %}
                            {%for post in post_list%}
                            <div class="card mb-4">
                                <div class="card-body">
                                    <h2 class="card-title h4">{{post.titulo}}</h2>
                                    <p class="card-text">{{post.descripcion}}</p>
                                </div>
                            </div>
                        {% endfor %}
                        {% endif %}

                            <!-- Blog post-->
                    </div>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-header">Categoriass</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        {%for cat in catgories_list%}
                                        <li><a href="{% url 'Blog:cat_post' cat.id %}">{{cat.nombre}}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

Practica2/Blog/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- CABECERA -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">BLOG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="/Blog">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Bienvenido a mi blog</h1>
                </div>
            </div>
        </header>
        <!-- CABECERA -->
        <!-- CONTENIDO -->
        {% block content %}
        {% endblock %}
        <!-- CONTENIDO -->
        <!-- PIE DE PAGINA -->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- PIE DE PAGINA -->
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>